### ISSUE TITLE
A simple trouble i think you will fix easily

### ISSUE THREAD

**Issue by pistachit1** [Strong-Moon/Instagram-Account-Creator#1]
When the automation opens the problem is that I am prompted to accept cookies which means I have to keep an eye on it. 

Another problem that I don't really know how to solve is that the account is automatically suspended, what can I do? .

**Comment by livacorp** [comment]
The reason for asking you to accept cookies is because of the proxy. Try a different proxy.

**Comment by Strong-Moon** [comment]
Now, I did everything the instagram bot does one by one with my own e-mail address. And the account was suspended again. I thought maybe it wasn't because we used temporary email. And the second thing I thought was that when opening the account with the bot, it was happening very quickly, so I thought my account might be suspended, but it wasn't both. The result didn't change. I will research on this topic.
